- src/blocker.rs
- src/filters/network.rs
Closes #12
Please see Issue #12 for a more detailed description of the option and the need for it
> Implements `$badfilter` option

- lib/index.js
- native/Cargo.lock
- native/Cargo.toml
- native/src/lib.rs
- package-lock.json
- package.json
- src/filter_lists/default.rs
- src/filter_lists/mod.rs
- src/filter_lists/regions.rs
- src/lib.rs
- src/lists.rs
Ports default and regions block lists information from https://github.com/brave/ad-block/tree/master/lists
Exposes the lists through the Node wrapper
> Lists metadata

- Cargo.lock
- Cargo.toml
- benches/bench_matching.rs
- native/Cargo.lock
- native/Cargo.toml
- package-lock.json
- package.json
- src/filters/network.rs
- src/request.rs
- src/url_parser/mod.rs
- src/url_parser/parser.rs
- tests/ublock-coverage.rs
A handful of optimisations streamlining URL parsing and extended benchmark for the case
> Optimisations v2

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- examples/example.rs
- src/blocker.rs
- src/filters/network.rs
adds full executable example and updates flate2 dependency to attempt to work around linker error on windows
> enables travis builds

- native/Cargo.lock
- native/Cargo.toml
- native/src/lib.rs
- package-lock.json
- package.json
- src/blocker.rs
- src/engine.rs
- extra result field in case error happens in processing request
- `new AdBlockClient.Engine` accepts JSON object for second argument specifying `debug` and `optimize` parameters
- utility method checking if provided 3 arguments (url, source_url, type) form a valid request
> updates Node APIs

- src/resources/mod.rs
Solution thanks to https://github.com/serde-rs/serde/issues/1413#issuecomment-494892266
> Deserialize from Cow<str> instead of &str (fixes #55)

- Cargo.lock
- Cargo.toml
- package-lock.json
- package.json
@AndriusA I will publish this to NPM, but I don't have permission to publish on crates.io
> Bump version to 0.2.2

- src/filter_lists/regions.rs
This includes the following polish filters from https://github.com/brave/ad-block/issues/146
Just need a check on language/title, used google to translate "Privacy" and "Supplemental".
> Include Polish Anti-adblock filters

- Cargo.lock
- Cargo.toml
- native/Cargo.lock
- native/Cargo.toml
- package-lock.json
- package.json
- src/filter_lists/default.rs
- src/filter_lists/regions.rs
- src/lists.rs
- Makes the title field for each region formatted and capitalized more consistently
- Adds a description (desc) field for each region
- Remove duplicate Indonesian list
- Add / correct a few lang entires
> add desc field for each filter list, remove duplicates and clean up existing regional filter list entries

- src/filter_lists/regions.rs
rebased version of https://github.com/brave/adblock-rust/pull/76
> Update component ids and base 64 fields to make them all unique

- src/filter_lists/regions.rs
> Fix 109: Fix component id and public key for Adblock Plus Lithuania

- src/filters/network.rs
> Remove FROM_HTTP/HTTPS flags from websocket rules

- Cargo.lock
- Cargo.toml
- src/cosmetic_filter_cache.rs
> Remove psl dependency, just use addr

- Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2020-0059
> Update reqwest and futures (RUSTSEC-2020-0059)

- Cargo.lock
- Cargo.toml
Fixes https://github.com/brave/adblock-rust/issues/147
> update lifeguard to 0.6.1

- tests/live.rs
Relates to https://github.com/brave/devops/issues/4356
> Update adblock-data endpoint

- Cargo.lock
- Cargo.toml
- benches/bench_redirect_performance.rs
- src/url_parser/mod.rs
Fixes https://github.com/addr-rs/addr/issues/12
> bump `addr` version to support older Rust compilers

- README.md
- native/Cargo.lock
- native/Cargo.toml
- native/build.rs
- native/index.js
- native/src/lib.rs
- package-lock.json
- package.json
Fixes https://github.com/brave/adblock-rust/issues/167
> Update Neon bindings to use N-API

- src/resources/resource_assembler.rs
Fixes https://github.com/brave/adblock-rust/issues/187
> Support multiple aliases for resources from scriptlets.js

- Cargo.lock
- Cargo.toml
- src/filters/cosmetic.rs
- src/lists.rs
> Harden CSS validation to forbid opening comments in cosmetic filter selectors

- src/blocker.rs
- src/engine.rs
- src/filters/regex_manager.rs
Resolves https://github.com/brave/adblock-rust/issues/250
> Regex manager minor improvements

- src/optimizer.rs
Resolves https://github.com/brave/adblock-rust/issues/255
> Fusion optimization now able to return regular patterns

- src/engine.rs
- src/filters/network.rs
- src/request.rs
- src/url_parser/parser.rs
This PR fixes issue #242 Support for better match-case regex filters.
> Support for better match-case regex filters

- src/lib.rs
- src/regex_manager.rs
> `RegexManager` is `Send`

- Cargo.lock
- Cargo.toml
- src/blocker.rs
- src/content_blocking.rs
- src/filters/cosmetic.rs
- src/filters/network.rs
- src/lists.rs
- src/request.rs
- src/resources/mod.rs
- src/resources/resource_assembler.rs
- src/resources/scriptlet_resource_storage.rs
Closes https://github.com/brave/adblock-rust/issues/262
> switch from `twoway` to `memchr` and replace existing stdlib methods

- src/resources/scriptlet_resource_storage.rs
> Handle quotes in scriptlet arguments

- tests/live.rs
Code changes to support the upcoming format update in https://github.com/brave/adblock-resources/pull/103
> New list catalog format

- src/lists.rs
It seems that there are quite a few lists that have the suffix ` (update frequency)` included in the `Expires` special comment. `ExpiresInterval::try_from` fails if this suffix exists. If this is intended, feel free to close this PR.
This also increases permissiveness for the plurality of the time unit; i.e. `1 hours` and `2 hour` would be acceptable values. This adjustment can be removed if need be.
> Increase permissiveness when parsing the `Expires` special comment

- src/content_blocking.rs
Fixes #336.
Just ignoring the rules for now; the code can be improved to accept them later.
> Don't crash when converting content blocking rules with $from option

- src/filters/cosmetic.rs
- src/lists.rs
For https://github.com/brave/brave-browser/issues/36039
> Forbid adguard cosmetic modifiers for now

- src/blocker.rs
- src/filters/network.rs
> Only apply removeparam to document/subdocument/xhr by default

- src/filters/cosmetic.rs
these aren't supported, so they shouldn't return a successful parse result
> return parse error for generic procedural filters

- Cargo.lock
- Cargo.toml
- benches/bench_redirect_performance.rs
- src/blocker.rs
- src/cosmetic_filter_cache.rs
- src/engine.rs
- src/resources/mod.rs
- src/resources/resource_assembler.rs
- src/resources/resource_storage.rs
- tests/matching.rs
> Bump base64 (0.9.x)

- Cargo.lock
- Cargo.toml
`cargo tree` output: 
[cargo_tree.txt](https://github.com/user-attachments/files/20558231/cargo_tree.txt)
> Update some deps to address sec alerts

- src/filters/unsafe_tools.rs
Actually, we don't have strong guaranties that `vec<u8>` will be aligned to 4 bytes on 32-bit architecture. It's an allocator-specific behavior despite I doubt that it's possible in production.
The PR adds a backup path if the vector isn't aligned.
Founded via https://github.com/rust-lang/miri.
`cargo +nightly miri test blocker::unit_tests::blocker_tests::get_csp_directives -- --nocapture`
P.S. The issue was presented in the original flatbuffer branch.
> Add safe alignment for flatbuffer

- Cargo.toml
- benches/bench_redirect_performance.rs
- src/blocker.rs
- src/content_blocking.rs
- src/filters/cosmetic.rs
- src/filters/network.rs
- tests/unit/resources/resource_assembler.rs
The PR cleans up the most of clippy issues.
> Fix the rest clippy issues
