brave/adblock-rust

src/filters/network.rs
Updates network filter tests to include all permutations of domain subsetting cases, mirroring uBlock Origin behaviour.
I.e. in the case of filter `adv$domain=~example.com|foo.example.com` and request URL = `http://example.net/adv` it does not match when issued from:
- http://example.com
- http://foo.example.com
- http://subfoo.foo.example.com
- http://bar.example.com
- http://anotherexample.com
Closes #5
=> Network filter domain option subsetting

src/blocker.rs, src/engine.rs, src/filters/network.rs, tests/legacy_harness.rs
Modifies the engine API to accommodate both options:
- Engine uses builder pattern to choose which tags should be used
- Result structure exposes additional boolean field `explicit_cancel` to signal when a filter with the option set matches
=> Implements Brave-specific filter options `tag` and `explicitcancel`

src/engine.rs, src/request.rs, tests/ublock-coverage.rs
Introduces public method for explicitly specifying:
- the hostname of the URL as already available
- hostname instead of full source url
- third-partiness of a request as an Option<bool> (None means undecided and need to compute)
=> Adds blocker engine method to use pre-parsed hostnames

.gitignore, Cargo.lock, Cargo.toml, benches/bench_url.rs, native/Cargo.lock, native/Cargo.toml, package-lock.json, package.json, src/blocker.rs, src/filters/network.rs, src/lib.rs, src/lists.rs, src/optimizer.rs, src/request.rs, src/url_parser/mod.rs, src/url_parser/parser.rs, src/url_parser/parser_full.rs, src/url_parser/parser_regex.rs, src/utils.rs, tests/ublock-coverage.rs
Optimisations to get in under the performance budget:
- implements optimisation that merges together equivalent rules with different domain options
- memory copying/allocation optimisations across request parsing and tokenisation
Also removes full-string domain option matching from compile-time option-enabled features
squeezes in under the performance target by ~5%
=> Performance Optimisations

Cargo.lock, native/Cargo.lock, native/Cargo.toml
As per  https://github.com/neon-bindings/neon/pull/410
=> patches Neon dependency to make library Node 12 compatible

src/engine.rs, src/filters/network.rs, tests/ublock-coverage.rs
Fixes the case with filter tokenisation where `||www.facebook.com/*/plugin` does not get picked up when matching `https://www.facebook.com/v3.2/plugins/comments.ph`
Adds test case to catch regressions if engine tags get dropped when deserialising
=> Filter fixes

src/blocker.rs, src/engine.rs, tests/legacy_harness.rs
retain tags of current instance, do not serialize.
when deserializing, tags of the existing instance (the one we are recreating lists into) are maintained
=> changes tag retention behaviour

README.md, native/src/lib.rs, src/blocker.rs
Check the updated README for usage example - _both_ the client and the `check` call have an extra `debug = true` parameter:
- the one in the client retains string representation of rules
- the one in the `check` returns detailed information object rather than only `true` or `false` for a match
=> adds more detailed info to Node wrapper response

native/src/lib.rs, src/blocker.rs, src/engine.rs, tests/legacy_harness.rs
- `tagExists` and `clearTags` methods in the Node API
- `addFilter` method in the Node API
About adding filters: rule optimisations that combine rules together make it non-trivial to check whether or not a rule already exists - a rule fused from multiple rules looks very different from the original rule. Checking for existence is therefore only available when optimisations are siwtched off. With optimisations siwtched on, a rule will get added without checking if it already exists
Note the outer-most `Engine` and corresponding Node APIs fail quietly, with only stderr logging in case of errors with existence checking or addition
=> adds functionality to add filters, check tags

Cargo.lock, Cargo.toml, README.md, benches/bench_matching.rs, benches/bench_rules.rs, benches/bench_url.rs, native/Cargo.lock, native/src/lib.rs, src/blocker.rs, src/engine.rs, src/lib.rs, src/resources.rs, src/utils.rs, tests/matching.rs, tests/ublock-coverage.rs
returns request content to use for requests matched on rules with `redirect` option
Closes #27
=> Implements uBO style polyfills for requests redirects

src/filter_lists/default.rs
Only merge after https://github.com/brave/adblock-lists/pull/124 is merged
=> Adds brave's list of disconnect rules, in adblock format, to the default set

src/filter_lists/default.rs, tests/live.rs
Ensures more of the polyfills (e.g. gpt.js) are returned for blocked requests
=> Includes uBO privacy.txt rules

package-lock.json
The currently used version of `neon-cli` has a dependency on a version of `handlebars` vulnerable to https://www.npmjs.com/advisories/1164. This upgrades `handlebars` to a fixed version.
=> Bump handlebars version

src/filters/network.rs
The function shouldn't panic on malformed input, Fixes #41
=> URL-after-hostname extraction avoids panic

data/test/fake-uBO-files/web_accessible_resources/google-analytics_analytics.js
Just sync recent patch from https://github.com/gorhill/uBlock/commit/8a1a8b103f5
=> Update google-analytics_analytics.js from https://github.com/gorhill/uBlock/commit/8a1a8b103f5

src/filter_lists/regions.rs
From the request: https://github.com/brave/ad-block/issues/229 
Unsure how to generate `component_id` and `base64_public_key`
=> Add ABPindo regional list brave/ad-block/#229 (WIP)

Cargo.toml, src/cosmetic_filter_cache.rs, src/engine.rs, src/filters/cosmetic.rs
The `cssparser` dependency calls `f64::powf`, which ends up linking to GLIBC_2.29 during `brave-core` CI builds. As a temporary workaround, making CSS validation an optional feature avoids this issue and shouldn't impact anything browser-side (CSS validation is only really needed in the CRX packager).
=> Optional CSS validation

src/filter_lists/default.rs
This will block Notification servers being used in Brave;
From our recent merge of Notification lists; https://github.com/brave/adblock-lists/pull/297
Any questions let me know.
=> Add Notification list to Brave

benches/bench_cosmetic_matching.rs, src/cosmetic_filter_cache.rs, src/engine.rs
Changes in `brave-core` to determine the first/third-partyness of affected page elements before applying a particular hide rule require access to the original selectors provided by the adblock engine. Building a stylesheet is now delegated to the caller.
=> Return list of selectors instead of a full stylesheet

src/blocker.rs
Although these two fields are unused on new versions of this repo, they are still serialized with dummy values to maintain backwards compatibility.
In particular, the second field is checked by older versions of the repo to determine if network blocking should be short-circuited. Thus, it's important that this field stores a value of `true` when serializing DAT files that will be loaded across different versions of `adblock-rust`.
=> Force unused load_network and load_cosmetic to true when serializing

README.md, native/Cargo.lock, native/Cargo.toml
The CRX packager will be generating serialized cosmetic rulesets; we want CSS validation there so we should enable it for the NPM package.
=> Enable CSS validation for NPM package

.npmignore
`index.node` is a large binary blob that's generated by `npm run install`; excluding it saves 5MB+ from the overall package size.
=> Clean index.node from npm package

src/filter_lists/default.rs
Now the list is officially supported by Easylist, we can move to this list. Makes it easier to make changes for me without needing to do a PR's. Also seems Eyeo might be keen to [include it.](https://gitlab.com/eyeo/adblockplus/abpui/adblockplusui/issues/701)
=> Move to Fanboy Notification List

src/filter_lists/regions.rs
Since Prebake Cookie hasn't been updated since 2018, we should replace this with Easylist Cookie.
Should help with cookie notices and resolve brave/brave-browser#5318 Will be more affective when we roll out cosmetic filtering.
Rebase of https://github.com/brave/adblock-rust/pull/67  (just had some merge issues)
Also re-did `component_id:` and `base64_public_key:`
PEM's also updated/uploaded.
=> Replace Prebake with Easylist Cookie

src/url_parser/parser.rs
Deprecated with https://github.com/rust-lang/rfcs/pull/2230
=> Remove deprecated method Error::description

src/filters/cosmetic.rs
The `nth-ancestor` procedural filter is currently not supported by `adblock-rust`, so it should be marked as unsupported syntax during parsing.
=> Forbid nth-ancestor cosmetic rules

src/filter_lists/regions.rs
Based on: https://github.com/brave/adblock-lists/issues/355 request. The most comprehensive list and also used by uBO as the default Japanese filter. 
Since ABP Japanese is not well supported and has many problematic filters; This change will help fix a few work arounds we needed to make (which will need to be reverted) 
https://github.com/brave/adblock-lists/pull/366
https://github.com/brave/adblock-lists/pull/319
https://github.com/brave/adblock-lists/pull/274
https://github.com/brave/adblock-lists/pull/270
More Japanese filter issues, https://github.com/brave/adblock-lists/pulls?q=is%3Apr+is%3Aclosed+label%3Aregional
=> Replace ABP-Japanese with Adguard Japanese (brave/adblock-lists#355)

src/filter_lists/regions.rs
Fix component_id and base64_public_key to match previous version used in https://github.com/brave/adblock-rust/pull/89
=> Adjust component_id/publickey to previous https://github.com/brave/adblock-rust/pull/89

src/filter_lists/regions.rs
Address has changed for the Lithuania List
https://github.com/EasyList-Lithuania/easylist_lithuania/issues/8
This commit is a quick fix for url and support url. Will fix the error reports of failures due to incorrect url address.
@AndriusA
=> Update Adblock url for Lithuania List

src/blocker.rs, src/cosmetic_filter_cache.rs, src/engine.rs, src/filters/network.rs
Adds support for `$generichide` exception rules (as well as the corresponding uBO-style alias, `$ghide`). These are network rules that prevent generic cosmetic element hiding from being applied to matching URLs.
This partially addresses https://github.com/brave/adblock-rust/issues/1.
=> Support generichide rules

src/blocker.rs, src/cosmetic_filter_cache.rs, src/data_format.rs, src/engine.rs, src/lib.rs
The way rmp_serde reads the Messagepack protocol structure (it only reads as far as needed to fill the struct, even if that's in the middle of a top-level list) means that the serialized version of `Blocker` would not be able to gain any new fields, which is problematic for #97 (which broke forwards-compatibility).
I've abstracted out serialization and deserialization logic into a module separate from `Blocker` and `CosmeticFilterCache`. My past decision to break the `CosmeticFilterCache` into a completely different serialization pass makes this a little uglier, but the extra layer of separation between the data format and internal representation makes future changes in both much easier.
The extra layer of translation is also very cheap performance-wise, considering that references are …
=> Decouple serialization/deserialization logic from internal data representation

src/filter_lists/default.rs
uBO has created a new file, basically splitting new additions to `filters-2020.txt` (maybe filters.txt was getting bloated?)
From the bottom of `https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt`
`! As of 2020-04-09 new domains for filters.txt will be added to filters-2020.txt sublist`
`!#include filters-2020.txt`
If its safe to merge @AndriusA :)
=> Add newly added filters-2020.txt from uBO

src/filter_lists/regions.rs
Fix #107 
1. `openssl rsa -in ad-block-updater-E71426E7-E898-401C-A195-177945415F38.pem -pubout -outform DER | openssl base64 -A`
2.  `openssl rsa -in ad-block-updater-E71426E7-E898-401C-A195-177945415F38.pem -pubout -outform DER | shasum -a 256 | head -c32 | tr 0-9a-f a-p`
3. `openssl rsa -in ad-block-updater-4C07DB6B-6377-4347-836D-68702CF1494A.pem -pubout -outform DER | openssl base64 -A`
4. `openssl rsa -in ad-block-updater-4C07DB6B-6377-4347-836D-68702CF1494A.pem -pubout -outform DER | shasum -a 256 | head -c32 | tr 0-9a-f a-p`
=> Fix 107: Fix the public key and component id for germany and indian list

src/blocker.rs
I adapted @AndriusA's comment in #85 to document `BlockerResult`. Thank you very much!
=> Add documentation for BlockerResult

Cargo.lock, Cargo.toml, benches/bench_redirect_performance.rs, src/filter_lists/mod.rs, tests/live.rs
The `http` crate recently had the following advisories released, as caught by `cargo audit`:
https://rustsec.org/advisories/RUSTSEC-2019-0033
https://rustsec.org/advisories/RUSTSEC-2019-0034
I've updated `reqwest` to `0.10`, which bumps `http` to a safely patched version.
=> Update reqwest to address cargo audit

Cargo.lock, Cargo.toml, native/Cargo.lock, native/Cargo.toml, src/request.rs, src/url_parser/mod.rs, tests/ublock-coverage.rs
Fixes #125. Users of the library can now disable the `embedded-domain-resolver` feature, implement `adblock::url_parser::ResolvesDomain` on a custom struct, and pass it to `adblock` using `adblock::url_parser::set_domain_resolver`.
Also should fix #86, by disabling the `addr` dependency on docs.rs builds.
=> Allow optionally setting an external host resolver implementation

src/blocker.rs, src/filters/network.rs
The blocker is not working under multiple rules with hostname regex.
For example, rules like
" ||alimc*.top^$domain=letv.com
||aa*.top^$domain=letv.com",
url like "https://r.alimc1.top/test.js" with domain "https://minisite.letv.com", which should matches but actually not.
I have figured out that the histogram of the tokens give the first fiter ("||alimc*.top^$domain=letv.com") the least count token "alimc", and url has the token "alimc1", so will not pick the bucket which contains the filter, then match failed.
I've tried to fix this by not recording the hostname of the filters with type of IS_HOSTNAME_REGEX .
=> Fix multiple hostname regex filters are not working properly.

src/filters/network.rs
This allows me to build [`python-adblock`](https://github.com/ArniDagur/python-adblock) with `PyO3` version `0.11.1` without any thread safety errors, if I disable the `object-pooling` feature.
=> Replace Rc with Arc

.travis.yml, Cargo.toml, native/Cargo.lock, native/Cargo.toml, native/index.js, native/src/lib.rs, src/content_blocking.rs, src/filters/cosmetic.rs, src/lib.rs, src/lists.rs
These changes should allow us to replace https://github.com/brave/ab2cb.
This initially supports all of the tests from https://github.com/brave/ab2cb/pull/5 (except for those containing `$popup` options, which are currently unsupported by `adblock-rust`).
=> Support for conversion to iOS/MacOS content blocking syntax

src/blocker.rs
Provides the necessary server-side fixes for #131.
Overall strategy is to map any `$important,redirect` rules at serverside DAT creation into two separate filters: one placed into the `importants` list, the other one placed into the `redirects` list without the `important` option. This mirrors uBlock Origin's `redirect`-splitting behavior. Then, later, the client will be updated to check redirects regardless of whether or not an important filter was found. This will allow `redirect`s to work even when a separate `important` rule exists.
Technically, the `redirect` option should not exist on the rule in the `important`s list. However, it's left in place not to break older clients.
This way, older clients will check for importants, find the `$important,redirect` rule, and use both options …
=> update DAT generation for part 1 of redirect/important fixes

src/blocker.rs, src/engine.rs
Follow up to #135, should be merged after those changes are shipped from the DAT server. Fixes #131.
=> Redirect important pt2

benches/bench_redirect_performance.rs, src/blocker.rs, src/content_blocking.rs, src/engine.rs, src/filters/network.rs, src/optimizer.rs, src/request.rs, src/utils.rs
The `$fuzzy` option appears to be specific to the Cliqz adblocker, but otherwise nonstandard and not present in any other adblockers or lists. The 32-bit `NetworkFilterMask` is close to getting fully used up; this is a good candidate for removal.
=> Remove $fuzzy option

src/blocker.rs, src/content_blocking.rs, src/engine.rs, src/filters/network.rs, tests/legacy_harness.rs
The approach here has some minor differences in what's blocked when compared to uBlock Origin, but will allow blocking most intentionally-blocked top-level documents while avoiding any ambiguous cases.
The compatibility differences stem from the fact that uBlock Origin handles the `document` option in a few different ways from other request types:
- top-level document blocking can be enabled implicitly by not specifying any other request types to block. However, top-level blocking enabled explicitly with a `$document` option and implicitly by not specifying any other network blocking types cannot affect each other in exception filters.
- eligibility for top-level document blocking is partially determined _after_ a filter has been matched, to discard any matches that do not start within …
=> Add support for document option on network filters

src/blocker.rs, src/engine.rs, src/filters/network.rs
Implements `Blocker::get_csp_directives`, which will allow querying the CSP directives from rules with `$csp` options so that they can be injected into a document or subdocument.
=> Support querying CSP directives

Cargo.toml, data/test/fake-uBO-files/redirect-engine2.js, data/test/fake-uBO-files/redirect-engine3.js, data/test/fake-uBO-files/web_accessible_resources/amazon_apstag.js, data/test/fake-uBO-files/web_accessible_resources/click-to-load.html, src/resources/resource_assembler.rs
https://github.com/gorhill/uBlock/commit/59169209850c54c31d94990f0c956281fe43eb03 introduced a new `params` field to each resource in `redirectableResources`, which caused the parser here to break.
Additionally, https://github.com/brave/uBlock/commit/0b5f53923fc4fd7e6927ce57cd9226a61bcbdb88 introduced `alias` values that are lists of strings rather than just a single string.
=> Support newer versions of uBlock Origin's resource library

data/test/fake-uBO-files/scriptlets2.js, src/resources/resource_assembler.rs
`json-prune` has the following comment in-line with its definition:
```javascript
/// json-prune.js
//
//  When no "prune paths" argument is provided, the scriptlet is
//  used for logging purpose and the "needle paths" argument is
//  used to filter logging output.
//
//  https://github.com/uBlockOrigin/uBlock-issues/issues/1545
//  - Add support for "remove everything if needle matches" case
//
```
The lines starting with `/// ` are part of the "format", and the lines starting with `// ` are handled by the parser, but the lines with no spaces afterwards (just `//`) are left in the scriptlet (even in upstream uBO). This causes issues if newlines are stripped, like `adblock-rust` has been doing.
To fix this, I've removed the newline stripping, and also added code to remove lines that are …
=> Prevent empty line comments in scriptlets from wreaking havoc

Cargo.lock, Cargo.toml, src/blocker.rs, src/data_format/legacy.rs, src/data_format/mod.rs, src/data_format/v0.rs, src/engine.rs, src/lib.rs, src/utils.rs
Progress towards https://github.com/brave/adblock-rust/issues/153.
For compatibility during upgrades, the existing gzip format will still be written and read. adblock-rust 0.4 will switch over to writing the new v0 brotli format, and the legacy gzip format will be removed at some point in the future.
=> Support brotli-encoded data format

src/blocker.rs
First implementation step of [this plan](https://github.com/brave/adblock-rust/issues/169#issuecomment-916471765).
> DAT packager side, begin duplicating any redirect filter, and adding it to `Blocker::redirects`. This should not change any behavior for existing clients.
=> Always duplicate redirect rules into `Blocker::redirects`

src/blocker.rs, src/engine.rs
Second implementation step of [this plan](https://github.com/brave/adblock-rust/issues/169#issuecomment-916471765).
> When updated DATs are available, begin treating redirects as independent from blocking/exception filters. This means exceptions for blocking should only be looked for in `Blocker::exceptions`, and exceptions for redirections should only be looked for in `Blocker::redirects`. `Blocker::redirects` should be checked for all matches rather than the first match (similar to `$csp`), and results should be combined accordingly. At this point, a redirection exception should always occur whenever a blocking exception occurs, but the code should be ready to handle the case when they do not occur together.
This will require a minor version bump. Even though there are no breaking …
=> Modify redirect semantics in preparation for redirect-rule support

benches/bench_matching.rs, benches/bench_redirect_performance.rs, benches/bench_rules.rs, data/matching-test-requests.json, examples/example.rs, examples/generate-dat.rs, native/src/lib.rs, src/blocker.rs, src/content_blocking.rs, src/engine.rs, src/filters/network.rs, src/lists.rs, src/optimizer.rs, tests/hashing_test.rs, tests/legacy_harness.rs, tests/live.rs, tests/matching.rs, tests/simple_use.rs, tests/ublock-coverage.rs
Add a new filter option to `adblock` called `redirect-url` (similar to `redirect=`) that allows loading of replacement resources via a URL instead of having to bundle all replacement resources in the client.
=> `redirect-url` filter option

.npmignore
`benches` cannot be excluded because the paths are referenced by `Cargo.toml`. This causes `npm install` to fail, even though the benchmarks are unused by the bindings.
The biggest saving comes from the removal of `docs/algo.png`.
`npm publish --dry-run` before:
```
npm notice package size:  523.0 kB
npm notice unpacked size: 1.2 MB
```
after:
```
npm notice package size:  138.3 kB
npm notice unpacked size: 711.0 kB
```
=> Remove docs and test code from npm package bundle

README.md
Previously got an error:
```
error[E0308]: mismatched types
--> src/main.rs:15:43
|
15 |     let blocker = Engine::from_filter_set(&filter_set, true);
|                                           ^^^^^^^^^^^
|                                           |
|                                           expected struct `FilterSet`, found `&FilterSet`
|                                           help: consider removing the borrow: `filter_set`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
error: could not compile `adblock_rs_test`
To learn more, run the command again with --verbose.
```
With the following version:
```
❯ cargo --version
cargo 1.51.0 (43b129a20 2021-03-16)
```
=> fix readme rust example

native/src/lib.rs, src/content_blocking.rs, src/lists.rs
It's useful to restrict the rule types parsed in cases other than conversion to content-blocking syntax; e.g. to restrict the size of a serialized DAT or lower memory overhead when not using both network and cosmetic filters.
This moves `RuleTypes` from an argument of `FilterSet::into_content_blocking()` into `ParseOptions` so that it can be applied on a per-filter or per-list basis and carry over to the `Engine` as well. It no longer requires the `content-blocking` feature to be enabled.
=> Move rule_types into ParseOptions

src/cosmetic_filter_cache.rs
Some scriptlets can throw exceptions. In those cases, any _other_ scriptlets injected on the page should continue executing independently. uBO does this by wrapping a try/catch block around each individual scriptlet.
=> Wrap each injected scriptlet with try/catch

Cargo.toml, README.md, src/data_format/legacy.rs, src/engine.rs, src/filters/network.rs, tests/live.rs
Resolves https://github.com/brave/adblock-rust/issues/203
Currently, the regexp field consumes a lot of memory because of the size of `Arc<RwLock<Option<Arc<CompiledRegex>>>>`.
It takes 40 bytes per item even when None is stored.
Most of the rules is non-regex(~90%).
This new approach takes 8 bytes per item for such rules.
It saves about 7Mb of memory in total.
Important note: this makes the engine not thread-safe and wrap under a new feature.
In fact, the browser uses adblock from a single sequence => we don't need to synchronize threads, the `thread-safety` feature should be disabled in browser to get benefit from the optimization.
```
Memory usage after loading data/rs-ABPFilterParserData.dat in tests/deserialization.rs
(Release, ubuntu x64, added jemallocator locally to calculate): …
```
=> Optimize regexp memory usage

.github/workflows/ci.yml, tests/live.rs
The endpoint for downloading the most recent DAT file was recently updated to require a service key; this allows the tests which required a live DAT to continue working by setting the `$brave_service_key` environment variable.
=> Add BraveServiceKey to live DAT tests

tests/live.rs
Followup to #211, since the variable is now uppercased
=> Update error message to use correct environment variable

Cargo.lock, Cargo.toml, src/blocker.rs, src/data_format/legacy.rs, src/data_format/v0.rs, src/engine.rs, src/filters/mod.rs, src/filters/network.rs, src/filters/regex_manager.rs, src/optimizer.rs, tests/legacy_harness.rs, tests/matching.rs
For https://github.com/brave/brave-browser/issues/26892
The idea is to use global regular expression storage instead of individual ones.
This allows to challenge the long-term regexp memory consumption problem in the next PRs.
A new `RegexManager` is in charge of matching/spawning/deleting regex instances. `NetworkFilter` is enforced to match using `RegexManager`.
Plans:
* track the last regex usage and drop the instance it after a few time;
* use less effective, but more memory-saving algorithms for some of the reg exps until it becomes a hot path;
Note:
* Using a standard hasher for u64 instead of AHasher results in 3% performance drop.. Not sure AHasher is the best option. I am open to other suggestions.
* Replacing a standard hasher in other places could also give a perf boost, worst …
=> Add a global RegexManager

.github/workflows/ci.yml, src/blocker.rs, src/regex_manager.rs
Disabling regex deletion on WASM targets for now, since `std::time` is not available. Also adding `wasm32-unknown-unknown` target to CI.
=> Fix WASM builds

.github/workflows/ci.yml
There is a regression where `lifeguard` dependency is being used even though `object-pooling` feature is not enabled. This was not caught by CI because CI builds and test only with `--all-features`.
```
[arni][/…/arni/src/adblock-rust][nodefaultfeatures-ci]% cargo test --no-default-features --tests --no-fail-fast
Compiling adblock v0.7.2 (/Users/arni/src/adblock-rust)
error[E0433]: failed to resolve: use of undeclared crate or module `lifeguard`
--> src/blocker.rs:380:25
|
380 |         request_tokens: lifeguard::Recycled<Vec<u64>>,
|                         ^^^^^^^^^ use of undeclared crate or module `lifeguard`
warning: unused import: `super::*`
--> src/url_parser/mod.rs:134:9
|
134 |     use super::*;
|         ^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
For more …
```
=> Add CI steps for `--no-default-features`

Cargo.lock, Cargo.toml, benches/bench_cosmetic_matching.rs
Update the criterion benchmarking utility to 0.4 to address audit warnings about the deprecated cbor crate.
=> Bump criterion to 0.4

src/blocker.rs
=> make request_tokens a slice to build correctly without lifeguard

src/content_blocking.rs
It might be possible to correctly convert the failing examples here at some point, but in the meantime this safeguard is important to ensure that the rulesets can be loaded.
(closes #272)
=> Forbid content blocking rules with non-ASCII characters

js/index.js, js/src/lib.rs
Closes #290 (cc @eggplants)
I'd still like to experiment with making `exceptions` an opaque struct to avoid serialization/deserialization overhead, but this should otherwise be functional if you'd like to start testing it.
```js
const urlCosmeticResources = engine.urlCosmeticResources('https://youtube.com');
const hiddenClassIdSelectors = engine.hiddenClassIdSelectors(['ad'], [], urlCosmeticResources.exceptions);
```
=> Expose cosmetic filtering methods to JS bindings

js/Cargo.lock, js/Cargo.toml, js/src/lib.rs
Closes https://github.com/brave/adblock-rust/issues/304
Unblocks https://github.com/brave/adblock-rust/pull/279
This allows us to remove `neon-serde`, which has a history of being only transiently maintained by various members of the community over time. This also [supposedly](https://github.com/neon-bindings/neon/issues/213#issuecomment-1353898233) provides better performance, although I haven't benchmarked it myself.
Ideally it can be replaced by an upstream solution eventually, but it seems to be an overall improvement already.
=> use JSON for FFI instead of `neon_serde`

src/blocker.rs
For cr121 we started to use 1.76 rust with a in-place iteration issue that results in excessive memory consumption.
`rustc 1.76.0-dev (df0295f07175acc7325ce3ca4152eb05752af1f2-3-llvmorg-18-init-12938-geb1d5065 chromium)`
This PR fixes the most critical code path that reduces the memory to about the original size.
=> Fix excessive memory usage for Rust 1.76

src/engine.rs, src/filters/network.rs, src/optimizer.rs
According to https://docs.rs/regex/latest/regex/#unicode-can-impact-memory-usage-and-search-speed the unicode flag in regex (which is enabled by default) can have unintended memory consequences. As a result, I observed that disabling this flag resulted in the built network filter regexes from easylist and easyprivacy end up using **a tenth** the memory that it would otherwise.
Unicode characters in urls are converted to ascii using punycode and url component encoding by browsers:
```
https://example-tesT߶.com/tesT߶  ->  https://xn--example-test-1ju.com/tesT%DF%B6
```
Hence, there is no reason to continue having the unicode flag enabled on network filters. All tests continue to pass after disabling it.
Also, as an extra bonus, the `check_matching_equivalent` test, which compares with …
=> Disable unicode in network filter regex

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, js/Cargo.lock
Unclear if this can be exploited, but upgrading should mitigate https://rustsec.org/advisories/RUSTSEC-2024-0421.
=> Update `idna` to v1.0

Cargo.lock, Cargo.toml, README.md, src/blocker.rs, src/data_format/v0.rs, src/engine.rs, src/filters/network_matchers.rs, src/lib.rs, src/request.rs, tests/unit/blocker.rs, tests/unit/request.rs
Bench performance has been improved a little.
`check`, `check_all` functions are simplified.
=> Code structure follow up #3.

benches/bench_rules.rs
The PR adds a benchmark to measure loading from serialized data (the content of a .dat file)
=> add brave-list-deserialize perf test

.github/scripts/run-benchmarks.sh, .github/workflows/perf-ci.yml, benches/bench_matching.rs
The PR:
* ~~Runs `cargo bench` for `master` to use it as a more reliable reference.~~ (need to merge `.github/scripts/run-benchmarks.sh first`)
* create a .sh file to launch the benchmarks 
* Set alert-threshold to 10%
* Limit the number of samples to 10 (speed up the CI)
=> Improve perf CI

tests/live.rs
This is more robust than assuming the 0th element in the list is the only relevant one, and fixes the currently broken live test.
=> respect default list metadata during live tests

Cargo.lock, Cargo.toml, src/filters/cosmetic.rs, tests/unit/engine.rs, tests/unit/filters/cosmetic.rs
The purpose of this update is to align the `selectors` version with what is currently used for other dependencies in Brave Browser, however this actually fixes a subtle issue relating to escaping special characters that occurs in 3 filter rules from our default lists. Tests added and updated to reflect the fix.
=> Update `selectors` crate to v0.26

src/data_format/storage.rs, tests/unit/engine.rs
closes #524 
(This is already fixed in the 0.11.x branch; this is just a fix for the 0.10.x series)
=> Add removeparam filters to the serialized data format
